# Generated by Django 4.0 on 2021-12-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('companyname', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Not Called', 'Not Called'), ('Wrong Number', 'Wrong Number'), ('Called/Not Reachable', 'Called/Not Reachable'), ('Called/Postponed', 'Called/Postponed'), ('Called/Accepted', 'Called/Accepted'), ('Emailed/Awaiting Response', 'Emailed/Awaiting Response'), ('Emailed/Declined', 'Emailed/Declined'), ('Emailed/Confirmed', 'Emailed/Confirmed')], max_length=70)),
                ('interview', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Undecided', 'Undecided')], max_length=70)),
                ('hrcount', models.PositiveIntegerField()),
                ('dept', models.CharField(max_length=70)),
                ('transport', models.CharField(choices=[('Own Transport', 'Own Transport'), ('College Cab', 'College Cab')], max_length=70)),
                ('extra_comments', models.TextField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
