# Generated by Django 4.0 on 2021-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
