# Generated by Django 3.2.9 on 2021-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0003_alter_hr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='search',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
