# Generated by Django 3.2.9 on 2021-12-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0004_hr_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='search',
        ),
    ]
