# Generated by Django 4.0 on 2021-12-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0005_remove_hr_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='dtoc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='internship',
            field=models.BooleanField(default=False),
        ),
    ]
