# Generated by Django 4.0 on 2021-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0006_hr_dtoc_hr_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
