# Generated by Django 4.0 on 2021-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_features', '0007_hr_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
