# Generated by Django 4.0 on 2021-12-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('team_ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_eds.teameds')),
            ],
        ),
    ]
