# Generated by Django 4.0 on 2021-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_eds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teameds',
            name='team_name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
